#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Paths
const cssPath = path.join(__dirname, '../public/assets/fonts/icons/font-icons.css');
const dataPath = path.join(__dirname, '../src/data/icons-data.ts');

console.log('🔄 Generating icons data from font CSS...');

try {
  // Read the generated CSS file
  const cssContent = fs.readFileSync(cssPath, 'utf8');
  
  // Extract icon class names using regex
  const iconMatches = cssContent.match(/\.icon-([^:]+)::before/g);
  
  if (!iconMatches) {
    console.log('❌ No icons found in CSS file');
    process.exit(1);
  }
  
  // Extract clean icon names and build data
  const icons = iconMatches.map(match => {
    const iconName = match.replace('.icon-', '').replace('::before', '');
    return {
      name: iconName,
      className: `icon-${iconName}`,
      displayName: iconName.split('-').map(word => 
        word.charAt(0).toUpperCase() + word.slice(1)
      ).join(' '),
      category: iconName.split('-')[0] || 'general'
    };
  });

  // Group by category
  const iconsByCategory = icons.reduce((acc, icon) => {
    if (!acc[icon.category]) {
      acc[icon.category] = [];
    }
    acc[icon.category].push(icon);
    return acc;
  }, {});
  
  console.log(`✅ Found ${icons.length} icons in ${Object.keys(iconsByCategory).length} categories`);
  
  // Generate TypeScript data file
  const tsContent = `// Auto-generated icons data
// Generated from ${path.relative(__dirname, cssPath)}
// Do not edit this file manually - run 'pnpm run sync-icons' to regenerate

export interface IconData {
  name: string;
  className: string;
  displayName: string;
  category: string;
}

export interface IconsByCategory {
  [category: string]: IconData[];
}

// All available icons
export const iconsData: IconData[] = ${JSON.stringify(icons, null, 2)};

// Icons grouped by category
export const iconsByCategory: IconsByCategory = ${JSON.stringify(iconsByCategory, null, 2)};

// Available categories
export const iconCategories = ${JSON.stringify(Object.keys(iconsByCategory), null, 2)};

// Total count
export const totalIcons = ${icons.length};
`;

  // Write the TypeScript file
  fs.writeFileSync(dataPath, tsContent);
  
  console.log('✅ Icons data generated successfully!');
  console.log(`📄 Generated: ${dataPath}`);
  console.log(`📊 Categories: ${Object.keys(iconsByCategory).join(', ')}`);
  
} catch (error) {
  console.error('❌ Error generating icons data:', error.message);
  process.exit(1);
}