// Auto-generated icons data
// Generated from ../public/assets/fonts/icons/font-icons.css
// Do not edit this file manually - run 'pnpm run sync-icons' to regenerate

export interface IconData {
  name: string;
  className: string;
  displayName: string;
  category: string;
}

export interface IconsByCategory {
  [category: string]: IconData[];
}

// All available icons
export const iconsData: IconData[] = [
  {
    "name": "social-bluesky",
    "className": "icon-social-bluesky",
    "displayName": "Social Bluesky",
    "category": "social"
  },
  {
    "name": "social-facebook",
    "className": "icon-social-facebook",
    "displayName": "Social Facebook",
    "category": "social"
  },
  {
    "name": "social-instagram",
    "className": "icon-social-instagram",
    "displayName": "Social Instagram",
    "category": "social"
  },
  {
    "name": "social-linkedin",
    "className": "icon-social-linkedin",
    "displayName": "Social Linkedin",
    "category": "social"
  },
  {
    "name": "social-threads",
    "className": "icon-social-threads",
    "displayName": "Social Threads",
    "category": "social"
  },
  {
    "name": "social-youtube",
    "className": "icon-social-youtube",
    "displayName": "Social Youtube",
    "category": "social"
  }
];

// Icons grouped by category
export const iconsByCategory: IconsByCategory = {
  "social": [
    {
      "name": "social-bluesky",
      "className": "icon-social-bluesky",
      "displayName": "Social Bluesky",
      "category": "social"
    },
    {
      "name": "social-facebook",
      "className": "icon-social-facebook",
      "displayName": "Social Facebook",
      "category": "social"
    },
    {
      "name": "social-instagram",
      "className": "icon-social-instagram",
      "displayName": "Social Instagram",
      "category": "social"
    },
    {
      "name": "social-linkedin",
      "className": "icon-social-linkedin",
      "displayName": "Social Linkedin",
      "category": "social"
    },
    {
      "name": "social-threads",
      "className": "icon-social-threads",
      "displayName": "Social Threads",
      "category": "social"
    },
    {
      "name": "social-youtube",
      "className": "icon-social-youtube",
      "displayName": "Social Youtube",
      "category": "social"
    }
  ]
};

// Available categories
export const iconCategories = [
  "social"
];

// Total count
export const totalIcons = 6;
